post/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import include, path

from . import views

app_name = "post"
urlpatterns = [
    path("blog-list", views.blog_list, name="blog-list"),
    path("create-blog", views.create_blog, name="create-blog"),
    path("like-unlike-blog", views.like_unlike_blog, name="like-unlike-blog"),
]

social_networking_project/urls.py
"""
social_networking_project URL Configuration
"""

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView


urlpatterns = [
    path("rest/", include("rest_apis.urls")),
    path("", include("user.urls", namespace='user')),
    path("post/", include("post.urls", namespace='post')),
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
# from django.contrib.auth.decorators import login_required
from django.urls import include, path

from . import views

app_name = "user"
urlpatterns = [
    path("signup", views.signup, name="signup"),
    path("", views.login, name="login"),
]

templates/base2.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Base Page{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    {% block extra_script %}
    {% endblock %}
  </body>
</html>

templates/blog_list.html
{% extends 'base2.html' %}

{% block content %}
 <div class="col-md-8 offset-md-2">
<a href="{% url 'post:create-blog' %}" class="btn btn-primary">Create Blog</a>
    <h1>Blog Index</h1>
    <hr>
    {% for blog in blog_list %}
    <h2><a href="#">{{ blog.title }}</a></h2>
    <small>
        {{ blog.created_at}} |&nbsp;
        Author:&nbsp;
        <a href="#">
            {{ blog.author.username }}
        </a>&nbsp;
    </small>
    <p>{{ blog.content | slice:":400" }}...</p>
    <a href="#">Total Like: {{ blog.liked|length }}</a>
    <form method="post" action="{% url 'post:like-unlike-blog' %}" id="login-form">
        {% csrf_token %}
        <input type="hidden" class="form-control" id="user_id" name="user_id" value={{user.id}}>
        <input type="hidden" class="form-control" id="blog_id" name="blog_id" value={{blog.id}}>
        <button type="submit" class="btn btn-primary" name="submit" value="like">Like</button>
        <button type="submit" class="btn btn-danger" name="submit" value="unlike">Dislike</button>
    </form>
    {% endfor %}
</div>
{% endblock %}

templates/create_blog.html
{% extends 'base2.html' %}

{% block content %}
<div class="container">
  <h2>Create Blog</h2>
  <form method="post" action="{% url 'post:create-blog' %}" id="create-blog-form">
  <div class="form-group">
    <label for="title">Title</label>
    <input type="text" class="form-control" id="title" placeholder="Blog Title", name="title" required>
  </div>
  <div class="form-group">
    <label for="description">Description</label>
    <textarea class="form-control" id="description" rows="3" name="content" required></textarea>
  </div>
  <input type="hidden" class="form-control" id="author" name="author_id" value={{user.id}}>
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="{% url 'post:blog-list' %}" class="btn btn-primary">Back</a>
</form>
</div>
{% endblock %}

templates/login.html
{% extends 'base2.html' %}

{% block content %}
<div class="container">
  {% if error_msg %}<div class="alert alert-danger" role="alert">{{error_msg}}</div>{% endif %}
  <h2>Login Page</h2>
  <form method="post" action="{% url 'user:login' %}" id="login-form">
  <div class="form-group">
    <label for="exampleInputEmail1">Username</label>
    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="username">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
  </div>
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Login</button>
  <a href="{% url 'user:signup' %}" class="btn btn-primary">SignUp</a>
</form>
</div>
{% endblock %}

templates/signup.html
{% extends 'base2.html' %}

{% block content %}
<div class="container">
  <h2>Sign Up </h2>
  <form method="post" action="{% url 'user:signup' %}", id="signup-form">
  <div class="form-group">
    <label for="exampleInputEmail1">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" name="email" required>
    {% if email  %}<small id="passwordHelp" class="text-danger">{{email}}</small>{% endif %}  
  </div>
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" class="form-control" id="username" name="username" required>
    {% if username  %}<small id="passwordHelp" class="text-danger">{{username}}</small>{% endif %}  
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" name="password" required>
    {% if password  %}<small id="passwordHelp" class="text-danger">{{password}}</small>{% endif %}  
  </div>
  <div class="form-group">
    <label for="exampleInputPassword2">Repeat Password</label>
    <input type="password" class="form-control" id="exampleInputPassword2" name="password2" required>
  </div>
  <div class="form-group">
    <label for="first_name">First Name</label>
    <input type="text" class="form-control" id="first_name" name="first_name" required>
    {% if first_name  %}<small id="passwordHelp" class="text-danger">{{first_name}}</small>{% endif %}  
  </div>
  <div class="form-group">
    <label for="last_name">Last Name</label>
    <input type="text" class="form-control" id="last_name" name="last_name" required>
    {% if last_name  %}<small id="passwordHelp" class="text-danger">{{last_name}}</small>{% endif %}  
  </div>
  {% csrf_token %}
  <button type="submit" class="btn btn-primary">Sign Up</button>
  <a href="{% url 'user:login' %}" class="btn btn-primary">Back to Login</a>
</form>
</div>
{% endblock %}